### ISSUE TITLE
Próxima Versão

### ISSUE THREAD

**Issue by mileo** [erpbrasil/erpbrasil.edoc#27]
- [x] Nota de Serviços Paulistana;
   - [x] Solução para o problema de assinatura: 
- [x] Nota de Serviços ISSNET;
- [x] Refatoração da nf-e conforme PR #15 

@marcelsavegnago @luismalta @rvalyi

**Comment by marcelsavegnago** [comment]
ISSNet já está rodando bem.  Vou dar uma uma organizada nas branchs da nsfelib.issnet este final de semana.
